# Datatypes
     None Type          an object that doesn't contain any value
     Numeric Type       int, float, complex
     Sequences          str, bytes, bytearray, list, tuple, range  
     Sets               
     Mappings

### Assigning Numeric Variables

In [50]:
a=13
b=108
c= -66
print(a,b,c)
print(type(a)) # to check datatype

13 108 -66
<class 'int'>


In [51]:
a= 2.5
b= 35.8
c= 250.0
print(a,b,c)
print(type(c)) # to check datatype 

2.5 35.8 250.0
<class 'float'>


### Assigning Binary,Complex,Hexadecimal and Octal

#### Complex

In [52]:
x= 2+3j  # will always be j 
print(x) 
print(type(x))

(2+3j)
<class 'complex'>


#### Binary, Hexa, Octa

In [53]:
a= 0B1010
print(a) #Will Print in Decimal/int type
print(type(a))

b=0XFF
print(b) #Will Print in Decimal/int type
print(type(b))

c=0O4567 
print(c)  #Will Print in Decimal/int type
print(type(c))

10
<class 'int'>
255
<class 'int'>
2423
<class 'int'>


### Boolean

In [54]:
g= True
print(g)
print(type(g))
print(5>4) # This is how we use bool

True
<class 'bool'>
True


### DataType Conversion
    Converting one variable type to another

In [55]:
a=15
b=float(a)

c=2.6
d=int(c)

e=bin(a)
f=hex(a)
g=oct(a)

print(b,d,e,f,g)

15.0 2 0b1111 0xf 0o17


# Sequences/Collections
    list, tuple, String, Set, Dictionary, bytearray, bytes

### String

In [56]:
s= 'You are the best'
a= """ God is 
    one who
    made this world"""
print(s*3)
print(s[1]) # Indexing to get particular part of a string
print(len(a)) # to calculate length of string: counts " " also
print("\n\n")

#Slicing
print(s[0:5])
print(s[-5:-1])
print(s[:10])
print(s[4:])
print("\n\n")

# Steps in Slicing
print(s[0:15:2]) #every second number from 0th element
print("\n\n")

# Strip the spaces
b= "  hello i am a robot  "
print(b)
print(b.strip()) # Removing both left and right spaces
print(b.lstrip()) # Removing only left space
print(b.rstrip()) # Removing only right space
print("\n\n")
# More string function
print(s.find('are',0,10)) # s.find('word to find in string',from where to start, from where to end)
print(s.count('t')) # to count the 'substring' in the string
print(s.upper())
print(s.lower())
print(s.title())

You are the bestYou are the bestYou are the best
o
40



You a
 bes
You are th
are the best



Yuaetebs



  hello i am a robot  
hello i am a robot
hello i am a robot  
  hello i am a robot



4
2
YOU ARE THE BEST
you are the best
You Are The Best


In [1]:
from difflib import get_close_matches # it provides the words of the closest match to a string from a list
get_close_matches('abc',['abcd','xyz','cdf'])

['abcd']

In [3]:
get_close_matches('abc',['abcd','abcde','zab'],cutoff=0.8) #cutoff is the proportion/accuracy value to match the word
# it will show the word which matches 80% to the string

['abcd']

In [4]:
get_close_matches('abc',['abcd','abcde','zab'])
# the point is that the first string in the list will always be the closest value

['abcd', 'abcde', 'zab']

### List

In [57]:
lst_1=[] # empty list
print(lst1)
lst=[1,2,3.5,'Gaurav',4.3]
print("Original List:",lst)
print(lst[2]) #Indexing
print(lst[1:4]) #Slicing
print("\n\n")

# Adding and Removing elements
lst_1.append('Gaurav')
print(lst_1)
lst_1.remove('Gaurav') # Removing an element by its name
print(lst_1)
del(lst[1]) # Removing an element by its index
print(lst)
print("\n\n")

a=[1,2,3,4,5,6]
# More functions on list
print(max(a))
print(min(a))
a.insert(4,67) # lst.insert(index,value)
print(a)
a.sort() #in ascending order
print(a)
a.sort(reverse=True)
print(a)

NameError: name 'lst1' is not defined

### Tuple
    Lists which can't be modified ,i.e, no insertion, no deletion, no slicing
    indicated by ()

In [ ]:
empty=()
tpl=(1,2,3,4,5,6,2,'gaurav')
tpl_1=(40,) # tuple of single element
print(tpl)
print(type(tpl_1))
print(tpl.count(2))
print(tpl*3)  #Repetition
print(tpl.index("gaurav")) #finding element index

a=[1,2,3,"hello",4.5]
b=tuple(a)
print(type(a))
print(type(b))

## Set
    Doesn't allow repetition,Slicing,Indexing as it doesn't have elements arranged in order
    Defined in {}    

In [ ]:
s={1,2,3,"hello",5.5,1,2}
print(s) #As could be seen, duplicate elements are not allowed
s.update([44,55,66])
print(s)
s.remove(3)
print(s)
# Frozen set, no deletion and insertion can occur
f=frozenset(s)
'''
f.update(['gaurav']) 
f.remove(66) Shows error in both cases
'''


## Range
    

In [ ]:
r=range(5)
for i in r:
    print(i) # 4 spaces before are indentation,leave them as it is
    
j=range(1,15,2)
print('range(start,stop(excluded),step)')
for h in j:
    print(h)

## Bytes and bytearray
    bytes:- No modification can be done, value can't be more than 255
    both accept only integer values and no indexing and slicing can be done.

In [ ]:
lst= [1,2,3,244]
print(type(lst))
b=bytes(lst) # to specify a byte maximum in a list should be 255 & can't take string and float
print(type(b))

c=bytearray(lst)
c[2]=33
for i in c:
    print(i)

## Dictionary
    {
        key:value
        }

In [ ]:
dict={1:"john",2:"hello",3:"cute"}
print(dict)
print("\n")
for i in dict.values():
    print(i)
print("\n")
for j in dict.keys():
    print(j)
print("\n")    
# INSERTION
dict[4]="hi!!"
print(dict)
print("\n")
# INDEXING
print(dict[2])
print("\n")
# DELETION
del dict[4]
print(dict)

# Operators and Operands

### Arthemetic Operators
    + :- Addition
    - :- Subtraction
    * :- Multiplication
    / :- Division
    //:- Integer Division  Returns integer quotient
    **:- Exponent 

In [ ]:
a=10
b=5
print("Addition",a+b)
print("Subtraction",a-b)
print("Multiplication",a*b)
print("Division",a/b)
print("Integer division",a//b)
print("Exponent",a**b)

### Assignment Operator
    = :- Assigns values
    Compound Operators
    +=
    -=
    *=
    /=
    //=
    **=
    %=

In [ ]:
a,b=10,5
a+=b
print(a)
a**=b
print(a)

### Comparison Operators
    ==
    <
    >
    <=
    >=
   Returns a Boolean Value

In [ ]:
#Example
print(3>4)
print(4<=4)

### Logical Operators
    and, or, not
    X and Y
    X or Y
    not X
    X,Y are either Boolean values or expressions which return boolean values

In [ ]:
print((3>2 and 5<8))
print(not(3>2 and 5<8))

# Input and Output functons
    input() function for input
    print() function for output

### print()

In [ ]:
print() #nothing will show
print("hello me")
print("hello this is \n gaurav") #newlline character
a,b=3,4
print(a,b,sep=",,")# sep:- separates a and b

# String Formatting
name="Gaurav"
marks= 94.5678
print("Name is",name,"marks are",marks)
print("Name is %s marks are %.3f"%(name,marks)) # %s:-string, %f:- float, %i:- integer
print("Name is {} marks are {}".format(name,marks))
print("Name is {0} marks are {1}".format(name,marks))

### input()

In [ ]:
n=input("Enter a number: ")
print(n,type(n))
#typecasting
s=int(input("Enter a number: "))
print(s,type(s))

### Reading Multiple inputs

In [ ]:
lst=[x for x in input("Enter numbers separated by comma").split(",")] #By default split considers space
print(lst)

# Flow Control Statements
    Conditional:- if, if..else, if..elif..else
    Looping:- while,for
    Transfer:- break, continue, pass, return

### Conditional Statements

In [65]:
# Checking whether a number is odd or even
n=int(input("Enter the number: "))
if n==0:
    print("0 is neither odd nor even")
elif n%2==0:
    print(n,"is even")
else:
    print(n,"is odd")

Enter the number: 5
5 is odd


### Looping Statements

In [69]:
# Using While loop find Odd numbers between two given numbers
x=int(input("Minimum number "))
y=int(input("Maximum number "))
i=x
if x%2 == 0: i=x+1
while i<=y:
    print(i)
    i+=2

Minimum number 1
Maximum number 10
1
3
5
7
9


In [70]:
# Using For loop find product for number in a list
list=[1,2,3,4,5,6]
prod=1
for i in list:
    prod*=i
print("Product is:",prod)

# Using for loop print numbers from 50 to 70
lst=[]
for j in range(50,71):
    lst.append(j)
print(lst)    

Product is: 720
[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70]


In [71]:
# Using for loop show the multiplication number of a table
s=int(input("Enter the number"))
for h in range(1,11):
    print(s,"X",h,"=",h*s)

Enter the number6
6 X 1 = 6
6 X 2 = 12
6 X 3 = 18
6 X 4 = 24
6 X 5 = 30
6 X 6 = 36
6 X 7 = 42
6 X 8 = 48
6 X 9 = 54
6 X 10 = 60


### Transfer Statements

In [ ]:
# Break the loop if 5 is present
lst=[1,2,3,4,6,7,5,8,9,0]
for i in lst:
    if(i==5):
        break;
    print(i)

In [ ]:
# print 1 to 20, skip multiples of 3
for i in range(1,21):
    if i%3==0:
        continue;
    print(i)

In [ ]:
# Enter number only greater than 10
x=int(input("Enter number greater than 10: "))
assert x>10, "Wrong number entered " # if it is true then code will continue, 
#the statement will appear if it is False, Statement is optional
print("You entered",x)

# Command Line Arguments
    - Another way to accept the inputs
    - Input will be passed to the program as an argument from command prompt
    - sys module is used
    - sys.argv contains the list in string form
    - Elements can be accessed with indexing, where index 0 contains filename and rest are arguments
    - Execute
        - Write program
        - Save with .py extension
        - Open Command Prompt
        - Change the path to where the program is being saved
        - py filename.py arg1 arg2 arg3 (Arguments)

In [ ]:
import sys
lst=sys.argv
for i in lst:
    print(i)
!python python_notes.ipynb 123 345 345


# Functions

In [60]:
# A function which prints average of 2 numbers
def average(a,b):# a,b are parameters
    print("Average of two numbers is",(a+b)/2)
average(10,20)

Average of two numbers is 15.0


In [61]:
# Return the result of same function
def average(a,b):
    return (a+b)/2
s=average(10,20)
print(s)
print(average(10,20)) # other method

15.0
15.0


In [62]:
# Returning Multiple values
def calc(a,b):
    x=a+b
    y=a-b
    z=a*b
    u=a/b
    return x,y,z,u # result will be returned as a tuple
result = calc(10,5)
print(result)

(15, 5, 50, 2.0)


### Global and Local Variables
    Global variables: Can be accessed anywhere in the program.
    Local variables: Can be accessed only inside the funciton.

In [63]:
x= 108 # Global variable
def num():
    x=340 # Local variable
    print(x)
    print(globals()['x']) # Accessing global variable inside the function
print(x)
num()
# Assigning function to a variable
z=num # no function brackets (no num())
z() # accessing function through a variable

108
340
108
340
108


### Function inside another function

In [59]:
def display(name):
    def message(): # this can only be accessed inside the function
        return "Hello "
    result= message()+name
    return result
display("Gaurav")

'Hello Gaurav'

### Passing function as a parameter to other

In [58]:
def display(fun):
    return "Hello "+fun
def name():
    return "Gaurav"
display(name())    

'Hello Gaurav'

### Returning functions

In [45]:
def display():
    def message():
        return "Hello"
    return message
fun=display() # here we are getting function message
print(fun()) # invoking the function message

Hello


In [46]:
def fun(lst):
    return lst
print(fun([1,2,3,4,5]))

[1, 2, 3, 4, 5]


### Recursion
    Function calling itself
    Steps:
    - First, define the end condition
    - Then define the else condition

In [47]:
# Calculate the factorial of a number
def factorial(n):
    if n==0:
        return 1
    else:
        return n*factorial(n-1)
print(factorial(3))    

6


### Keyword Arguments

In [48]:
def average(a,b):
    return (a+b)/2
print(average(12,14)) # the sequence matters
print(average(b=10,a=20)) # here the sequence of variables doesn't matters but keywords matter

13.0
15.0


### Default Arguments

In [49]:
def average(a=10,b=30): # If no argument is passed then these will be considered
    return (a+b)/2
print(average())
print(average(b=50))

20.0
30.0


# Lambdas
    Anonymous function with no name
    General Syntax: lambda argument_list:expression
    But usually it is not used like this.

In [36]:
#Cube of a number
f = lambda n:n**3
print(f(2))

8


In [37]:
# Create a lambda that will return "YES" if the given number is even and "NO" if the given number is odd
f = lambda x:"YES" if x%2==0 else "NO"
print(f(10))
print(f(9))

YES
NO


In [38]:
# Passing more than one numbers to a lambda
f= lambda a,b: a+b
print(f(10,20))

30


In [39]:
# Retrive only even numbers list from a list
# filter function takes two arguments filter(lambda function, sequence)
lst=[1,2,10,11,33,44]
result =list(filter(lambda x:x%2==0, lst)) #converting filter object into list
print(result) 

[2, 10, 44]


In [40]:
# Manipulating values of lists using map function
# Syntax: map(lambda function, sequence)
lst= [1,2,3,4,5,6]
result = list(map(lambda n:n*2,lst))
print(result)

[2, 4, 6, 8, 10, 12]


In [41]:
# Use reduce function to calculate the sum of all elements in a list
from functools import reduce
lst=[1,2,3,4,5]
result=reduce(lambda x,y:x+y,lst)
print(result)

15


In [42]:
# Decorator: a function which performs an additional logic on a function and accepts and returns a functions
# Since it returns a function so it must also have an inner function which gets returned
# Double a number using decor function
def decor(fun):
    def inner():
        result=fun() #invoking the parameter function
        return result*2
    return inner

def num():
    return 5

resultfun=decor(num)
print(resultfun())

10


In [43]:
'''make a function hello() which will retun "Hello" and a decorator which the decorate the string by adding "How are you" 
at he end'''
def decorfun(fun):
    def inner(n):
        result= fun(n)
        result += " How are you?"
        return result
    return inner

@decorfun
def hello(name):
    return "Hello "+ name
print(hello('Gaurav'))

Hello Gaurav How are you?


In [44]:
"""Generators are the functions that returns 'sequence of values'
but it uses a yield statement which stores each value in the sequence and at last returns it"""
# Creating a custom generator function
def customgen(x,y):
    while x<y:
        yield x # stores elements in the memory
        x+=1
result = customgen(10,15)
for i in result:
    print(i)

10
11
12
13
14


# List Comprehensions
    l = [expression for item in iterable if condition]

In [34]:
lst = [int(x) for x in input("Enter the three numbers separated by space").split()]
print(lst)

Enter the three numbers separated by space2 4 5
[2, 4, 5]


In [35]:
''' Using list comprehension, get the even numbers from  1 to 20'''
'''lst = [x for x in range(2,21,2)]
print(lst)'''
lst = [x for x in range(1,21) if x%2==0]
print(lst)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [31]:
# Product the numbers of two different lists and store the result in new list
a=[1,2,3,4,5]
b=[5,4,3,2,1]
z=[]
'''for i in range(len(a)):
        a.append(a[i]*b[i])'''
z= [a[i]*b[i] for i in range(len(a))]
print(z)

[5, 8, 9, 8, 5]


In [30]:
# Common elements in a list
a = [1,2,3,4,5]
b = [3,4,5,6,7]
c=[]
'''for i in a:
    if i in b:
        c.append(i)'''
c=[i for i in a if i in b]
print(c)        

[3, 4, 5]


# Object Oriented Programming
    Encapsulation
    Inheritance
    Abstraction
    Polymorphism
 All these 4 OOPs principle are applied by classes and objects
 Classes help us to create user defined datatype with the help of objects.

### Creating First Class

In [29]:
class Product:
    def __init__(self):   # constructor, self keyword stores values to the object address.
        self.name= 'IPhone'
        self.description= 'Its Awesome'
        self.price= 700

p1 = Product()
print(p1.name)
print(p1.description)
print(p1.price)

IPhone
Its Awesome
700


### Parametrized Constructor

In [28]:
class Course:
    def __init__(self,name,ratings):
        self.name = name
        self.ratings = ratings

p1 = Course("Python",[1,2,4,5])
print(p1.name)
print(p1.ratings)

Python
[1, 2, 4, 5]


### Calling function using objects

In [27]:
class Course:
    def __init__(self,name,ratings):
        self.name = name
        self.ratings = ratings
    def average(self):
        number_of_ratings = len(self.ratings)
        avg= sum(self.ratings)/number_of_ratings
        print("Average rating is",avg)
        
p1 = Course("Python",[1,2,4,5])
print(p1.name)
print(p1.ratings)
p1.average()

Python
[1, 2, 4, 5]
Average rating is 3.0


### Create Setter and Getter

In [26]:
class Programmer:
    def setName(self,n):
        self.name = n
        
    def getName(self):
        return self.name
    
    def setSalary(self,sal):
        self.salary = sal
    
    def getSalary(self):
        return self.salary
    
    def setTechnologies(self,techs):
        self.technologies = techs
        
    def getTechnologies(self):
        return self.technologies
    
p1 = Programmer()
p1.setName("John")
p1.setSalary(5000)
p1.setTechnologies(["Java","Sprint","Python"])

print(p1.getName())
print(p1.getSalary())
print(p1.getTechnologies())

John
5000
['Java', 'Sprint', 'Python']


In [25]:
# Using display function
class Course:
    def __init__(self,name,ratings):
        self.name = name
        self.ratings = ratings
    def display(self):
        print(self.name)
        print(self.ratings)

p1 = Course("Python",[1,2,4,5])
p1.display()

Python
[1, 2, 4, 5]


### Static Field

In [24]:
class student:
    major = "ME"
    
    def __init__(self,rollno,name):
        self.rollno = rollno
        self.name = name
        
s1 = student(45,"John")
s2 = student(65,"Gaurav")
print(s1.major)
print(s2.major)
print(s1.rollno)
print(s2.rollno)

ME
ME
45
65


### Count the number of object

In [23]:
class objectCounter:
    number_of_objects = 0
    def __init__(self):
        objectCounter.number_of_objects += 1
    
    def display():
        print(objectCounter.number_of_objects)

p1 = objectCounter()
p2 = objectCounter()
p3 = objectCounter()
objectCounter.display()

3


### Creating Inner Class

In [22]:
class Car:
    def __init__(self,make,year):
        self.make = make
        self.year = year
    
    class Engine:
        def __init__(self,number):
            self.number = number
        def start(self):
            print("Engine Started")

c = Car("BMW",2020)
e = c.Engine(1234)
e.start()

Engine Started


# Encapsulation
    Hiding the functionalities of the class using Private fields

In [21]:
'''class Student:
    def __init__(self):
        self.id = 123     # These are public fields hence can be accessed directly
        self.name = "John"
s = Student()
print(s.id) # Accessing public fields directly
print(s.name)'''
class Student:
    def __init__(self):
        self.__id = 123     # These are private fields hence can't be accessed directly
        self.__name = "John"
    def display(self):
        print(self.__id)
        print(self.__name)

s = Student()
s.display()
print(s._Student__id) # Another way to access private variables

123
John
123


# Inheritance
    Process of defining new object with the help of existing object

In [20]:
class BMW:
    def __init__(self,make,model,year):
        self.make = make
        self.model = model
        self.year = year
    def start(self):
        print("Starting the car")
    def stop(self):
        print("Stopping the car")
    
class ThreeSeries(BMW): # Inheriting the class
    def __init__(self,cruisecontrolEnabled,make,model,year): #in constructor, fields of parent class should be present to access in child class
        BMW.__init__(self,make,model,year)# The first line in child class constructor is to invoke parent class constructor
        self.cruisecontrolEnabled = cruisecontrolEnabled # new field only available in child class
        
    def display(self):
        print("Cruise Control Enabled",self.cruisecontrolEnabled)
        
class FiveSeries(BMW):
    def __init__(self,parkingAssistEnabled,make,model,year): #in constructor, fields of parent class should be present to access in child class
        BMW.__init__(self,make,model,year)# The first line in child class constructor is to invoke parent class constructor
        self.parkingAssistEnabled = parkingAssistEnabled # new field only available in child class
        
threeSeries = ThreeSeries(True,"BMW","328i","2018")
print(threeSeries.cruisecontrolEnabled)
print(threeSeries.make)
print(threeSeries.model)
print(threeSeries.year)

threeSeries.display() # dsiplay can only be accessed by the object of threeSeries class
# Inheriting the functionality from parent class
threeSeries.start()
threeSeries.stop()
# Same thing we can do with FiveSeries class. 

True
BMW
328i
2018
Cruise Control Enabled True
Starting the car
Stopping the car


In [19]:
class BMW:
    def __init__(self,make,model,year):
        self.make = make
        self.model = model
        self.year = year
    def start(self):
        print("Starting the car")
    def stop(self):
        print("Stopping the car")
    
class ThreeSeries(BMW): 
    def __init__(self,cruisecontrolEnabled,make,model,year): 
        super().__init__(make,model,year) # another way to invoke parent class constructor
        self.cruisecontrolEnabled = cruisecontrolEnabled 
        
    def display(self):
        print("Cruise Control Enabled",self.cruisecontrolEnabled)
        
    def start(self):# function overiding
        super().start() # to invoke parent class functions 
        print("Button start")    
        
threeSeries = ThreeSeries(True,"BMW","328i","2018")
# Sometimes we need to perform different fuction with same method name.
threeSeries.start()

Starting the car
Button start


# Polymorphism
    when a one single entity like an operator or a function performs many different tasks

### Duck Typing

In [18]:
class Duck:
    def talk(self):
        print("Quack Quack!")
class Human:
    def talk(self):
        print("Hello")
def callTalk(obj):
    obj.talk()
    
d = Duck()
callTalk(d)
h = Human()
callTalk(h)
# So, as you can see here, same functions performs different operations

Quack Quack!
Hello


### Operator overloading
    Eg, + operator is overloaded to perform multiple functions

In [17]:
x = 10
y = 20
print(x + y) # addition

s1 = "Hello "
s2 = "How are you"
print(s1 + s2) # String Concatenation

l1 = [1,2,3,4]
l2 = [5,6,7,8]
print(l1 + l2) # Appending

30
Hello How are you
[1, 2, 3, 4, 5, 6, 7, 8]


### Abstraction
    The object of class having extract method can't be created
    The child classes will have to implement abstract method if the parent class has abstract method
    the abstract method in parent class doesn't do anything

In [16]:
from abc import abstractmethod,ABC
class BMW(ABC):
    def __init__(self,make,model,year):
        self.make = make
        self.model = model
        self.year = year
    def start(self):
        print("Starting the car")
    def stop(self):
        print("Stopping the car")
    
    @abstractmethod
    def drive():
        pass # abstract function doesn't do anything in parent class
    
class ThreeSeries(BMW): 
    def __init__(self,cruisecontrolEnabled,make,model,year): 
        BMW.__init__(self,make,model,year)
        self.cruisecontrolEnabled = cruisecontrolEnabled 
        
    def display(self):
        print("Cruise Control Enabled",self.cruisecontrolEnabled)
        
    def drive():
        print("Car has started")
        
class FiveSeries(BMW):
    def __init__(self,parkingAssistEnabled,make,model,year): 
        BMW.__init__(self,make,model,year)
        self.parkingAssistEnabled = parkingAssistEnabled 
        
threeSeries = ThreeSeries(True,"BMW","328i","2018")
print(threeSeries.cruisecontrolEnabled)
print(threeSeries.make)
print(threeSeries.model)
print(threeSeries.year)

threeSeries.display() 
threeSeries.start()
threeSeries.stop()


True
BMW
328i
2018
Cruise Control Enabled True
Starting the car
Stopping the car


# Exception Handling, Assertions and Logging
Syntax:

    try:
        {code}
    except error_name:
        error statement
        
    else:
        if 'except' statement is not executed then
        'else' statement is executed.
        
    finally:
        if error occurs in a single statement of the code in 'try' then the compiler will directly 
        go to the execpt statement instead of reading the rest of the code.So, in 'finally', the other code is written
        to execute it.

In [15]:
try:
    f = open("myfile","w")
    a,b = [int(x) for x in input("Enter two numbers").split()]
    c = a/b
    f.write("Writing %d into file"%c)
except ZeroDivisionError:
    print("Division by zero is not allowed")
    print("Please enter a non-zero number")
finally:
    f.close()   # file will not be closed if code is written after error statement in 'try' block
    print("file closed")
print("Code after the exception")    

Enter two numbers4 0
Division by zero is not allowed
Please enter a non-zero number
file closed
Code after the exception


### Using Else

In [14]:
try:
    f = open("myfile","w")
    a,b = [int(x) for x in input("Enter two numbers").split()]
    c = a/b
    f.write("Writing %d into file"%c)
except ZeroDivisionError:
    print("Division by zero is not allowed")
    print("Please enter a non-zero number")
else: # executed when except block is not executed
    print("Non Zero number entered")
finally:
    f.close()   # file will not be closed if code is written after error statement in 'try' block
    print("file closed")
print("Code after the exception")   

Enter two numbers1 3
Non Zero number entered
file closed
Code after the exception


### Creating your own exception

In [13]:
class OvertheLimit(Exception):   # Exception is a built in class in python, to raise exception
    def __init__(self,msg):
        self.msg = msg # This message will be displayed in the error statement

def withdrawl(amount):
    if(amount > 500): # So, here instead of printing statement I want to raise an exception
        raise OvertheLimit("More than 500 can't be withdrawn")
        
s = int(input("Enter the amout to be withdrawn "))
withdrawl(s)

Enter the amout to be withdrawn 677


OvertheLimit: More than 500 can't be withdrawn

### Handling Errors

In [12]:
try:
    s = int(input("Enter an even number "))
    assert s%2 == 0, "Wrong or odd number entered"
except AssertionError as obj:
    print(obj)
    
print('After the Assertion')

Enter an even number 5
Wrong or odd number entered
After the Assertion


# Files
    Where we store our data.
    Types:
        Text File
        Binary File
    Opening file: f = open("finename / path to file","mode","buffer(optional)")
    Modes:
    Binary and Text respectively
     wb    w:- writes content from the beginning of the file, erase previous content
     rb    r:- read fro mthe beginning of the file
     ab    a:- add new content to the file after the continuition of the previous content
     w+b   w+:- Write and Read
     r+b   r+:- Read, Write and Append
     a+b   a+:- appending and reading
     xb    x:- exclusive mode, if a file already exist with the same name then it will throw an error

### Writing String to a File

In [72]:
f = open("Stringfile.txt","w") #opening the file
s = input("Enter Text: ") # Taking input from the user
f.write(s) # Writing string to file 
f.close() # CLosing the file

Enter Text: hwad njk knkjkjbh


### Reading a file

In [77]:
f = open("Stringfile.txt","r")
s = f.read() # Assigning the string to a variable
print(s)
f.close()

hwad njk knkjkjbh


### Writing Multiple Strings

In [78]:
f = open("MultipleStr.txt","w")
print("Enter Text (Type @ when you are done)")
s = ''
while s!='@':
    s = input()
    f.write(s + "\n") # To get each sentence in a new line
f.close()    

Enter Text (Type @ when you are done)
Hello this is Gaurav
You can be a Python Programmer
Just Work hard
Leave Bad company
@


### Checking if the file exist

In [80]:
import os,sys
if os.path.isfile("MultipleStr.txt"):  # it returns boolean value 'True' if file exist
    f = open("MultipleStr.txt","r")
else:
    print("File Doesn't exist")
    sys.exit() #program will terminate here and no code after it will be executed as file doesn't exist
    
s = f.read()
print(s)
f.close()

Hello this is Gaurav
You can be a Python Programmer
Just Work hard
Leave Bad company
@



# Regular Expressions
    Used to validate,search and change the substring in a string using some patterns
    Sequence characters:
    \d :- Digit
    \D:- Non Digit
    \s:- Whitespace
    \S:- Non Whitespace
    \w:- Any alphanumeric value
    \W:- Non alphanumeric
    \b:- Space around words
    \A:- Do search at the beginning of the string
    \Z:- Matches only at the end of the string

### search()
    Returns very first sub-string

In [5]:
import re
str = "Take up one idea. One idea at a time"
result = re.search(r'o\w\w',str) # searching sub-string in the 'str' , it returns object
# o\w\w :- word starts with 'o' and contains total 3 characters.
print(result.group()) # group method is used on that obbject

one


### findall() and match()
    findall():- From very beginnning to the end finds all substring matching the pattern and returns as a list
    match():- Matches the given pattern in the string at the very beginning

In [14]:
import re
str = "Take up one idea. one idea at a time"
result = re.search(r'O\w\w',str)
print(result)# Cannot use group() method on None
result = re.findall(r'o\w\w',str)
print(result)
result = re.match(r'T\w',str)
print(result.group()) # Works only on the first beginning string


None
['one', 'one']
Ta


### split()
    Splits the string into a multiple strings and returns them in a list.["str 1", "str 2"]

In [15]:
import re
str = "Take up 1 one idea.23 one idea 408 at a time"
result = re.split(r'\d+',str)
print(result)

['Take up ', ' one idea.', ' one idea ', ' at a time']


### Substitute

In [17]:
import re
str = "Take up one idea. one idea at a time"
result = re.sub(r'one','Two',str)
print(result)

Take up Two idea. Two idea at a time


### Sequence characters are used for single characters, Quantifiers can be used for multiple characters
    Like:
    + :- to specify one or more repetitions of the preceding sequence character.
        Eg, \d+ :- Means that Number can be either single or multiple digit
    * :- 0 or more repetitions of the preceding sequence character.
    ? :- 0 or 1 repetition of the preceding sequence character.
    {m}:- Exactly 'm' occurences of the preceding sequence character.
    {m,n}:- 'm' is the minimum and 'n' is the maximum occurences.By default, m:-0 and n=(infinity)

In [4]:
import re
str = "Take up One idea. One idea at a time"
result = re.findall(r'O\w+',str)
print(result)

['One', 'One']


In [5]:
import re
str = "Take up One idea. One idea at a time"
result = re.findall(r'O\w*',str)
print(result)

['One', 'One']


In [6]:
import re
str = "Take up One idea. One idea at a time"
result = re.findall(r'O\w?',str) # Exactly 0 or 1 character(\w:- alphabet)
print(result)

['On', 'On']


In [7]:
import re
str = "Take up One idea. One idea at a time"
result = re.findall(r'O\w{1,2}',str)
print(result)

['One', 'One']


### Matching Dates

In [9]:
import re
str = "Take up One 12-03-2020 idea. One idea 09-01-2021 at a time"
result = re.findall(r'\d{1,2}-\d{1,2}-\d{4}',str)
print(result)

['12-03-2020', '09-01-2021']


# Date and Time
    epoch is used to tell the current time in seconds

In [2]:
import time
epochseconds = time.time() # to get today's time in seconds
t= time.ctime(epochseconds) # to get today's time in day date hh:mm:ss year format
print(t)

Sun Jan 10 11:00:01 2021


In [3]:
import datetime
dt = datetime.datetime.today()
print("Current Date: {}/{}/{}".format(dt.day,dt.month,dt.year))
print("Current Time: {}:{}:{}".format(dt.hour,dt.minute,dt.second))

Current Date: 10/1/2021
Current Time: 11:2:40


### Combining Date and Time

In [5]:
from datetime import *
d = date(2021,1,10) # yyyy,m,dd format
t = time(11,7) # hour,min,second format
dt = datetime.combine(d,t)
print(dt)

2021-01-10 11:07:00


### Sorting Dates and sleeping program

In [11]:
from datetime import date
import time
ldates = []
d1 = date(2021,1,10)
d2 = date(2021,1,9)
d3 = date(2021,1,8)

ldates.append(d1)
ldates.append(d2)
ldates.append(d3)

ldates.sort()
time.sleep(3) # the program will sleep for 3 seconds before ececuting the next statement
for d in ldates:
    print(d)

2021-01-08
2021-01-09
2021-01-10


### Knowing execution time of the program

In [16]:
from datetime import date
import time

startTime = time.perf_counter()

ldates = []
d1 = date(2021,1,10)
d2 = date(2021,1,9)
d3 = date(2021,1,8)

ldates.append(d1)
ldates.append(d2)
ldates.append(d3)

ldates.sort()
#time.sleep(3)
for d in ldates:
    print(d)
    
endtime = time.perf_counter()
print("Execution TIme:",endtime-startTime)

2021-01-08
2021-01-09
2021-01-10
Execution TIme: 0.0015037999996820872


### Checking Credit Card Validation

In [22]:
from datetime import *

def validateCard(expdate):
    if expdate > datetime.now().date():
        print("Valid")
    else:
        print("Expired")
        
validateCard(date(2022,1,10))    
print(datetime.now())
print(datetime.today())

Valid
2021-01-10 12:10:21.762106
2021-01-10 12:10:21.762107


In [42]:
# Assignment
from datetime import *
class Address:
    def __init__(self,street,city,state,country,zipcode):
        self.street = street
        self.city = city
        self.state = state
        self.country = country
        self.zipcode = zipcode
class Venue:
    def __init__(self,name):
        self.name = name
        self.address = []
    def addaddress(self,Address):
        self.address.append(Address)
    
class Event:
    def __init__(self,startTime,endTime):
        self.startTime = startTime
        self.endTime = endTime
        self.venue = []
    def addvenues(self,venues):
        self.venue.append(venues)
        
a = Address(12,"Delhi","Delhi","India",110034)
v = Venue("Delhi Technological University")
e = Event(time(11,10),time(2,10))

v.addaddress(a)
e.addvenues(v)

print("Event Starts at {} and ends at {}".format(e.startTime,e.endTime))
for venue in e.venue:
    print(venue.name)
    for add in v.address:
        print('Street:{},City:{},State:{},Country:{},Zipcode:{}'.format(add.street,add.city,add.state,add.country,add.zipcode))

Event Starts at 11:10:00 and ends at 02:10:00
Delhi Technological University
Street:12,City:Delhi,State:Delhi,Country:India,Zipcode:110034


# Networking

### Downloading HTML

In [4]:
import urllib.request
try:
    url = urllib.request.urlopen("https://www.python.org/")
    content = url.read()
    url.close()
except urllib.error.HTTPError:
    print("The web page is not found")
    exit()

f = open('python.html','wb')
f.write(content)
f.close()

### Downloading an Image

In [6]:
import urllib.request
url = 'https://www.python.org/static/img/python-logo.png'
urllib.request.urlretrieve(url, 'python.png')

('python.png', <http.client.HTTPMessage at 0x206fc12e670>)

# Numpy

In [4]:
import numpy as np
# Creating Array
# An array can have variables of single datatype only
a = np.array([1,2,3,4,5])
b = np.array(['a','b','c','d','e'])
c = np.array(['Python','Data Manipulation','Data Visualisation'])
print(a)
print(b)
print(c)

[1 2 3 4 5]
['a' 'b' 'c' 'd' 'e']
['Python' 'Data Manipulation' 'Data Visualisation']


### linspace()/logspace()/zeros()/ones()

In [13]:
import numpy as np
print(np.linspace(1,100,10))  # Gives equally spaced 10 numbers in a range
print(np.logspace(1,20,num = 10)) #Gives 10 logarithmic numbers
print(np.arange(1,9)) # range() function in array
print(np.zeros(10)) # array containing 0s
print(np.ones(10)) # array containing 1s

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
[1.00000000e+01 1.29154967e+03 1.66810054e+05 2.15443469e+07
 2.78255940e+09 3.59381366e+11 4.64158883e+13 5.99484250e+15
 7.74263683e+17 1.00000000e+20]
[1 2 3 4 5 6 7 8]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### Basic Maths Function

In [19]:
import numpy as np
a = np.arange(1,10)
b = np.arange(11,20)
print(np.log(a))
print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(a+b) #Summation of elements of the array

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
45
5.0
1
[12 14 16 18 20 22 24 26 28]


### Array Comparison

In [29]:
from numpy import *
a1 = array([10,30,50,70,100])
a2 = array([20,40,60,80,100])
print(a1 >= a2)
print(a2 > a1)
print(any(a1 >= a2)) # Return 'True' if anyone element of a1 is equal to a2
print(all(a1 >= a2))# Return 'True' if all element of a1 is equal to a2


[False False False False  True]
[ True  True  True  True False]
True
False


In [35]:
from numpy import *
a1 = array([1,2,3,4,5,6])
a2 = array([2,1,1,6,7,8])

print(logical_and(a1>2,a1<5)) # logical operators in numpy arrays
print(where(a1%2!=0,a1,0)) # if number is odd then return elements of a1 else 0
# where() can also be used with multiple arrays
print(where(a1%2!=0,a1,a2))

[False False  True  True False False]
[1 0 3 0 5 0]
[1 1 3 6 5 8]


In [41]:
from numpy import *

a1 = arange(1,10)
a2 = a1.view()
a3 = a1.copy()
print('a1',a1)
print('a2',a2)
print('a3',a3)
print("After modification of a3")
a3[3] = 20 # Deep copy
print('a1',a1)
print('a3',a3) # change in element has no effect on original array
print('After modification of a2')
a2[3] = 40 # Shallow Copy
print('a1',a1)
print('a2',a2) # change in element of a2 has effect on original array

a1 [1 2 3 4 5 6 7 8 9]
a2 [1 2 3 4 5 6 7 8 9]
a3 [1 2 3 4 5 6 7 8 9]
After modification of a3
a1 [1 2 3 4 5 6 7 8 9]
a3 [ 1  2  3 20  5  6  7  8  9]
After modification of a2
a1 [ 1  2  3 40  5  6  7  8  9]
a2 [ 1  2  3 40  5  6  7  8  9]


### Slicing Array

In [44]:
from numpy import *
a1 = arange(3,12)
print(a1)
print(a1[1:5])
print(a1[::2])

[ 3  4  5  6  7  8  9 10 11]
[4 5 6 7]
[ 3  5  7  9 11]


### Multidimensional Array

In [58]:
a2 = array([[1,2,3],[4,5,6]])
a1 = array([1,2,3,4,5,6])
print(a2)
print(a1)
print('\n',a2.shape) 
print(a1.shape)
print(a2.reshape(3,2))
print('\n')
print(a1.dtype) # to know the datatype of the array
print(a2.dtype)
print('\n')
print(a2.flatten()) #Converts multi-dimensional array into 1-D
print(eye(3)) # for unit matrix of 3 X 3
print(ones((2,3),int)) # int datatype


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]

 (2, 3)
(6,)
[[1 2]
 [3 4]
 [5 6]]


int32
int32


[1 2 3 4 5 6]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 1 1]
 [1 1 1]]
